### ISSUE TITLE
Exemple.xml - Ajout id langue

### ISSUE THREAD

**Issue by Ammeister** [Ammeister/SupportGitGithub#2]
Imprécision dans le Header :

- [ ] Ajouter l'identifiant ISO du moyen haut allemand dans @ ident de la balise language ligne 53.

où trouver l'identifiant : https://fr.wikipedia.org/wiki/Moyen_haut_allemand

**Comment by Mareike2405** [comment]
Hello! Ich habe den issue geregelt ;) - glaube ich zumindest

**Comment by Ammeister** [comment]
résolu par #10
